### ISSUE TITLE
Seem plugin read only 10000 first lines

### ISSUE THREAD

**Issue by chtiland** [cosmocode/dokuwiki-plugin-statdisplay#34]
All stats displayed are from the first 10000 lines, what's wrong (E-mail notification is disabled) ?

**Comment by tmo26** [comment]
Same here (Release 2015-08-10a "Detritus"). 10000 lines are read, and after that, no new data is displayed.

**Comment by RaphaelWimmer** [comment]
There is an error in line 60 of helper/log.php:

`if($pos && ( ($size - $pos) > ($this->getConf('lines') * 150) )) return 0; // we want to have some minimal log data` 

should be 
`if($pos && ( ($size - $pos) < ($this->getConf('lines') * 150) )) return 0; // we want to have some minimal log data`

(i.e., a smaller sign instead of a greater sign is needed). 
In any case, the script will stop analysis if there are less than `lines` to parse (as configured in the settings).

**Comment by akeix** [comment]
Same here (Release 2015-08-10a "Detritus"). 10000 lines are read, and after that, no new data is displayed.

Even with the fix, the problem continues.

**Comment by chtiland** [comment]
I don't use this plugin any more, but http://www.dokuwiki.org/plugin:statistics instead.

**Comment by micgro42** [comment]
The cause of this issue was/is that the size of the chunk, as defined in the configuration, also determinates the approximate number of accesses that need to happen before another chunk is read. Hence reducing that number in the configuration means that the plugin updates faster, not only every 10.000 page accesses.

In today's version I have reduced that default number to 500. You may want to reduce or increase that number, depending on whether your wiki has few or many active users.
